### PR TITLE
Add fonts in various sizes for font scaling and adapt UI to it

### PR DESCRIPTION
**Pull request by m6c7l**
- add NotoSans(-Regular), font size = (13, 16, 20, 24, 32)
- add LucidaSans(-Regular), font size = (13, 16, 20, 24, 32)
- put fonts to /media/fonts
- add parameter "font" and options = ("NotoSans", "LucidaSans") to ini-files
- add parameter "font_scale" and options = (0, 1, 1.25, 1.5, 2) to ini-files
- add dynamic layout of buttons to launcher app to meet the various font sizes
- add viewport size adjustments to the apps
- _this pull request invalidates pull request https://github.com/bridgecommand/bc/pull/17_
- _this pull request addresses issue https://github.com/bridgecommand/bc/issues/16_

> This script has been used for the creation of the XML files and bitmaps:  https://gist.github.com/m6c7l/842d7aaecba97dda46d482e5e32ea5ad

BC5_font_scale

### CODE REVIEW

**Comment by bridgecommand** [comment]
Hi, thanks for this, likely to be very useful for larger screens. A couple of comments and questions:

- For me, with NotoSans, the vertical alignment of the characters seems off, particularly noticable with numeric characters (eg in the time)
- For LucidaSans, I think that the licence for this font isn't compatible with the GPL. Is there an alternative you could suggest?

**Comment by m6c7l** [comment]
Hi.
* Yes, you are right. The numbers in NotoSans are somewhat off. I had not recognized this since I was mostly checking the font in the launcher app :-) I will try to fix that.
* I accidentally mixed up Lucida (which is already part of Irrlicht) and Lucida Sans. I do not know an alternative except for OpenSans (Apache license, but is not considered compatible with GPLv2). Perhaps switching to a little bit more relaxed license is an option for BC 6? ;-)

**Comment by bridgecommand** [comment]
Hi, the Apache Licence for the fonts (Noto Sans and Open Sans) should be fine, there's no problem distributing these alongside the (GPL) main program. The problem with Lucida Sans is the commercial license.

**Comment by m6c7l** [comment]
Ok, does the font itself (and its license) need to be part of BC5 since Irrlicht is using just rendered bitmaps of these fonts?

**Pull request closed without merging**
