### PR TITLE
Add exit button, user needs to quit explicitly

### PR DESCRIPTION
**Pull request by m6c7l**

### CODE REVIEW

**Comment by bridgecommand** [comment]
Thanks, this seems like a good idea, and will work well on posix systems. 

fork() does not exist on Windows generally (except recent Windows Subsystem for Linux)
Would you be able to wrap the 'fork' in an '#ifndef _WIN32' preprocessor statement?

I think that the same effect can be achieved on Windows by changing the windows '_execl' statements into 'CreateProcess' ones. This will mean that the launcher process will continue running, rather than being replaced.

**Comment by m6c7l** [comment]
Uhhh, fork() is not available on Windows? I will check and modify to make it work :-)

**Comment by m6c7l** [comment]
changes are committed. however, i could not test if it works as expected. since shellexecute is already in action (to open the documentation from the launcher) i give it a shot.

**Comment by bridgecommand** [comment]
Thanks, I will test on Windows

**Comment by bridgecommand** [comment]
Thanks, this is ok on Windows now.

**Pull request merged**
