### PR TITLE
Housekeeping

### PR DESCRIPTION
**Pull request by m6c7l**
- another attempt of https://github.com/bridgecommand/bc/pull/27
- nothing has been deleted, just moved and only a few files have been slightly adapted to the new structure
- nevertheless, i would suggest not to put binaries (like .exe) to the repo, a better place for those would be the release/tag section without versioning,
- i tried to do my very best to keep the solution and project files (CodeBlocks, Visual Studio) and the auxiliary script files intact
- i think the changes affect the first impression of the repo (at least the README is shown without scrolling :-)), and
- makes contribution imho easier and more likely since most developers are at least familiar with such a repo structure
- preview here: https://github.com/m6c7l/bc/tree/repo_overhaul

### CODE REVIEW

**Comment by bridgecommand** [comment]
Thanks. I'll look at this over the coming week.

**Comment by dpservis** [comment]
Hi everyone,

I have a private repo of BridgeCommand and I have completely restructured the code by completely separating the business from visualization (there's somewhere a mention to MVC but really there's no MVC there...). One of the reasons that I attempted this was that I wanted to separate my own ship code and unit test it, the same for other classes. So I have several smaller projects now: OwnShip, Scene (everything GUI related), World, Assets, and Initializers (everything needed to initialize business from files). I have also isolated irr and removed the usage of irr typed in business so that it is not needed when testing and it is also possible to replace it eventually with a live library. Would such a structure be interesting for you?

**Comment by m6c7l** [comment]
Hi there,

I think MVC can definitely help to make things easier from several
points of view in the future in the BC project... I agree that there is
nothing like this nor another pattern implemented in the codebase - at
least not as obvious as it would be helpful in some way. So yes, I
think it would be a good step in the right direction to have that kind
of separation and guiding pattern in the codebase.

As a first step, could you somehow grant access to your repo for an
initial investigation about the changes you made in particular?



Am Freitag, dem 22.01.2021 um 13:35 -0800 schrieb dpservis:

**Comment by bridgecommand** [comment]
Yes, I would be interested in being able to see your changes, thanks.

**Comment by dpservis** [comment]
Hi,

thanks for the answer! Since there is interest in this, I will clean up my repo and make it public.

Kind regards

Dimitris

**Pull request merged**
